### ISSUE TITLE
pandas_read_xml

### ISSUE THREAD

**Issue by hporeddy32** [minchulkim87/pandas_read_xml#14]
I am getting -  list indices must be integers or slices, not str

when I try to use pandas_read_xml to parse xml file
Its throwing error when i give 4th parameter - FormDef

Ex., df = pdx.read_xml('metadata.xml', ['test1', 'child1', 'subchild1', 'subchild2']).pipe(fully_flatten)

Sample xml

attached zip

**Comment by hporeddy32** [comment]
xml :


<?xml version="1.0" encoding="UTF-8"?>
<ODM xmlns="http://www.cdisc.org/ns/odm/v1.3" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:ecos="http://www.eclinicalos.com/ns/odm_ext_v132/v1.0" xmlns:odm="http://www.cdisc.org/ns/odm/v1.3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" FileType="Transactional" ODMVersion="1.3.2" SourceSystem="eClinicalOS" xsi:schemaLocation="http://www.cdisc.org/ns/odm/v1.3 https://secure.clinicaldevelopment.ibm.com/odm/eCOS-ODM1-3-2.xsd">
  <Study OID="Study.eClinicalOS/proj35656">
    <GlobalVariables>
      <StudyName>SPARKLE</StudyName>
      <StudyDescription>THE ALPHA-MANNOSIDOSIS REGISTRY: A multi-centre, multi-country, non-interventional, prospective cohort, in alpha-mannosidosis patients</StudyDescription>
      <ProtocolName>CLI-LMZYMAA1-12</ProtocolName>
    </GlobalVariables>
    <MetaDataVersion Description="Initial revision of study" Name="Study Revision 1" OID="MV.1">
      <Protocol>
        <Description>
          <TranslatedText>Initial revision of study</TranslatedText>
        </Description>
        <StudyEventRef Mandatory="No" OrderNumber="1" StudyEventOID="SE.736786" />
        <StudyEventRef Mandatory="No" OrderNumber="2" StudyEventOID="SE.736788" />
        <StudyEventRef Mandatory="No" OrderNumber="3" StudyEventOID="SE.754850" />
        <StudyEventRef Mandatory="No" OrderNumber="4" StudyEventOID="SE.754853" />
        <StudyEventRef Mandatory="No" OrderNumber="5" StudyEventOID="SE.754862" />
        <StudyEventRef Mandatory="No" OrderNumber="6" StudyEventOID="SE.754863" />
        <StudyEventRef Mandatory="No" OrderNumber="7" StudyEventOID="SE.1088169" />
        <StudyEventRef Mandatory="No" OrderNumber="8" StudyEventOID="SE.754864" />
        <StudyEventRef Mandatory="No" OrderNumber="9" StudyEventOID="SE.754865" />
        <StudyEventRef Mandatory="No" OrderNumber="10" StudyEventOID="SE.754866" />
        <StudyEventRef Mandatory="No" OrderNumber="11" StudyEventOID="SE.754943" />
        <StudyEventRef Mandatory="No" OrderNumber="12" StudyEventOID="SE.754952" />
      </Protocol>
      <StudyEventDef Name="vINC" OID="SE.736786" Repeating="No" Type="Scheduled">
        <Description>
          <TranslatedText>Inclusion Visit</TranslatedText>
        </Description>
        <FormRef FormOID="FM.698817" Mandatory="No" OrderNumber="1" />
        <FormRef FormOID="FM.699714" Mandatory="No" OrderNumber="2" />
        <FormRef FormOID="FM.699716" Mandatory="No" OrderNumber="3" />
        <FormRef FormOID="FM.699718" Mandatory="No" OrderNumber="4" />
        <FormRef FormOID="FM.699726" Mandatory="No" OrderNumber="5" />
        <FormRef FormOID="FM.699721" Mandatory="No" OrderNumber="6" />
        <FormRef FormOID="FM.699722" Mandatory="No" OrderNumber="7" />
        <ecos:RevisionVisitPath VisitID="10" />
      </StudyEventDef>
      <FormDef Name="p2MWT" OID="FM.719747" Repeating="Yes">
	    <Description>
          <TranslatedText>2-Minute Walk Test (2MWT)</TranslatedText>
        </Description>
        <ItemGroupRef ItemGroupOID="IG.719747.MWT2" Mandatory="No" OrderNumber="1" />
        <ecos:RevisionPagePath IsEproPage="No" PageID="150" VisitID="20" />
        <ecos:RevisionPagePath IsEproPage="No" PageID="150" VisitID="30" />
        <ecos:RevisionPagePath IsEproPage="No" PageID="150" VisitID="50" />
        <ecos:RevisionPagePath IsEproPage="No" PageID="20" VisitID="120" />
      </FormDef>
	</MetaDataVersion>
  </Study>
</ODM>

**Comment by hporeddy32** [comment]
[metadata_18411.zip](https://github.com/minchulkim87/pandas_read_xml/files/7124435/metadata_18411.zip)

**Comment by minchulkim87** [comment]
Hi

For future reference, as with all markdown, you can use triple back ticks to include code.

```python
df = pdx.read_xml('metadata_18411.xml', ['ODM', 'Study', 'MetaDataVersion', 'FormDef']).pipe(fully_flatten)
```

I will take a look at the file in the meantime.

**Comment by minchulkim87** [comment]
Didn't expect to get the whole data file, but I did take a look. Hopefully there weren't any data I wasn't meant to see.
This XML schema is very poorly designed, so I understand your frustration. My tool helps you work with it a little bit, but you still need to play around and navigate the data structure.

For example, I see that you want to get to 'FormDef', which sits under the 'MetaDataVersion' tag (bad naming), but also, there are multiple MetaDataVersion tags (one of which is apparently a placeholder). Anyway, since there are multiple MetaDataVersion tags under which the FormDef tags sit, this is not the root that you should be trying to read.

- ODM
    - Study
        - MetaDataVersion
        - MetaDataVersion
            - FormDef
            - FormDef
        - MetaDataVersion
            - FormDef
            - FormDef
        - MetaDataVersion
            - FormDef
            - FormDef

Hopefully you can see that FormDef is in no way the "root" (or the "common" node) from which you can extract all the data.
This means that you first need to read with MetaDataVersion as your root, then select the FormDef.

Also note that, for reasons beyond me, but probably due to the ill-designed XML schema, the MetaDataVersion tags are not able to be read in as rows of data. so first I do this:

```python
df = pdx.read_xml('metadata_18411.zip', ['ODM', 'Study', 'MetaDataVersion'], root_is_rows=False)
```

Then you will see that one of the columns is FormDef, you can select that (perhaps keeping the metadata tags)
And perhaps cleaning the column names if you need

```python
df = df[['@Description', '@Name', '@OID', 'FormDef']]
df.columns = df.columns.str.replace('@', 'MetaData')
```

Then you can fully flatten the data. 

```python
form_defs = pdx.fully_flatten(df)
```

Which is probably what you were looking for.



Alternatively, you can auto separate the tables. This method itself requires a bit of exploration, but I have built this part of the package to help with the exploration too.

Since the MetaData are shared (since they are from the parent node of the node you are interested in), you can use that as the sort of Foreign Keys.

I've cleaned the names of the columns that belonged to MetaDataVersion tag, so that looks like this

```python
data = pdx.auto_separate_tables(df, ['MetaDataOID', 'MetaDataName', 'MetaDataDescription'])
```
This is a dictionary with each key being the table name and each value being the pandas dataframes.

You can take a look at what it generates yourself.

If you do have a look at the FormDef data, you will notice that there are one-to-many relations within the FormDef data. This tool can help you separate those at the FormDef level too.

```python
data = (df[['FormDef']]
        .pipe(pdx.auto_flatten)
        .pipe(pdx.auto_separate_tables, ['FormDef|@Name']))

data.keys()
```

You'll get these tables: 'Description', 'ItemGroupRef', 'ecos:RevisionPagePath', and 'FormDef'

Please have a closer look at the XML data to understand the structure, and please feel free to play around with pdx to navigate the data.
But also note that pandas now has a `read_xml` method, so my tool should be considered obsolete.

**Comment by hporeddy32** [comment]
thank you
