### ISSUE TITLE
fully_flatten throws a numpy.core._exceptions._ArrayMemoryError error

### ISSUE THREAD

**Issue by Michal-Zablocki** [minchulkim87/pandas_read_xml#15]
Hi, I have a very nested xml file and I tried to use your library on it. The function auto_flatten only goes a couple of levels deep (not deep enough), while if I try fully_flatten or run flatten in a loop multiple times my whole RAM gets eaten and in the end I get an error thrown at me. The xml is not huge, it has around 8 MB.

The error was:
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 5.97 GiB for an array with shape (22, 36415165) and data type object

By no means should there be need to allocate so much memory, I believe - the xml isn't that big.

I pandas_read_xml 0.3.1 pandas 1.4.2 and python 3.10.4 running.

**Comment by minchulkim87** [comment]
Hi.

Firstly, thank you for trying out pandas-read-xml. But since pandas now comes with read_xml, I don't think my package offers any value.

On that note, pandas also has its own methods for "explode" and "json_normalize" to do equivalent flattening. I only added flatten functions because XML schemas don't consistently result in the same data type for each column, compared with JSON.

To your particular problem, I can't say for sure without looking at your XML data, but I am quite confident that in your case the memory is genuinely going to run out - this can happen even for very small XML file if it contains multiple one-to-many relationships. Each time it explodes a column it will repeat every other columns.

Even if you had 10 columns, each with 10 elements stored as a single list, this would mean that a full explosion would result in 10^10 = 10,000,000,000 rows of data. This is why I caution against fully_flatten.

My advice is as follows:

1. Perform the "auto_flatten" (which stops at a point where I think has flattened all one-to-one columns while leaving the one-to-many columns as lists) and take a look at the dataframe.
2. Is there a "key" or an "id" column? If not, make one (for example, using .reset_index()). Then you could try "auto_separate_tables" to see if pandas-read-xml will separate out one-to-many structures into separate tables. Doing this will also perform flattening in the process.

Hope this helps, but also, I would consider using just pandas.
