### ISSUE TITLE
Error incompatible version when using with pandas >=1.0.3

### ISSUE THREAD

**Issue by hellocoldworld** [minchulkim87/pandas_read_xml#2]
Hello, first of all I want to congratulate you for this fanstastic project

I'm using this library alongside pandas==1.0.5 in my requirements, and when building a venv the following error appears:
 ```bash
ERROR: pandas-read-xml 0.0.5 has requirement certifi==2020.4.5.1, but you'll have certifi 2020.4.5.2 which is incompatible.
ERROR: pandas-read-xml 0.0.5 has requirement numpy==1.18.4, but you'll have numpy 1.18.5 which is incompatible.
ERROR: pandas-read-xml 0.0.5 has requirement pandas==1.0.3, but you'll have pandas 1.0.5 which is incompatible.
ERROR: pandas-read-xml 0.0.5 has requirement requests==2.23.0, but you'll have requests 2.24.0 which is incompatible.
ERROR: pandas-read-xml 0.0.5 has requirement six==1.14.0, but you'll have six 1.15.0 which is incompatible.
```
However no I found no trouble when using the library.

Shall this error be silenced?

Thank you in advance for your attention

**Comment by minchulkim87** [comment]
Hi

Thanks! I've seen these version difference errors when installing other packages before. It has never really been an issue.

I must admit, I am quite new to packaging things up. How would I silence these? I've assumed that the messages were just there to let the users know that there are version differences. Perhaps this is more of a pip issue rather than this particular package.

Kindest regards

Min

**Comment by hellocoldworld** [comment]
Hello Min, thanks you for your quick reply (and sorry for my own late attendance).

Although I'm also a newbie to packaging thing up, I think this is done by requiring a minimal and a maximal version instead of an exact match. I have open a PR #3 to fix this, please review it when you have a chance.

Regards
