### ISSUE TITLE
Reading xml from string, not from file?

### ISSUE THREAD

**Issue by RabbitJackTrade** [minchulkim87/pandas_read_xml#4]
As the title says, is there a way to load an xml string directly without first saving it to a file?

Thanks.

**Comment by minchulkim87** [comment]
Yes. The function:

```python
def read_xml_as_dataframe(xml: str, root_key_list: Optional[list]=None, transpose: bool=False) -> pd.DataFrame:
```

Does that.

You can use it by:

```python
import pandas_read_xml as pdx

xml = """
... the xml string ...
"""

df = pdx.read_xml_as_dataframe(xml)
```


Should I change the

```python
pdx.read_xml()
```

to attempt to read the xml string directly?

**Comment by RabbitJackTrade** [comment]
First - thanks, the function worked!
Second - yes, ideally the same function should be able to read from a string or a file. I don't believe separating the two operations contributes anything.
Thanks again.

**Comment by minchulkim87** [comment]
Thanks.

They weren't "separate operations" per se. The lower-level function reads the XML string while the higher-level function calls it after having read the .xml or .zip (or double .zip) files.

I wasn't sure whether to incorporate it in or not as pandas.read_csv() does not take CSV formatted string as input. But since pandas.read_json() does take in valid JSON strings, I guess it makes sense that pdx.read_xml() should also take in XML string.

Updated to version 0.0.6. You should be able to read from an XML string using read_xml().

Cheers
