### ISSUE TITLE
Unable to export DataFrame to CSV

### ISSUE THREAD

**Issue by cozyGalvinism** [minchulkim87/pandas_read_xml#5]
I have a really basic XML file for testing purposes:

```
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <row>
        <columnA>value</columnA>
        <columnB>2</columnB>
        <columnC>true</columnC>
    </row>
    <row>
        <columnA>value</columnA>
        <columnB>2</columnB>
        <columnC>true</columnC>
    </row>
    <row>
        <columnA>value</columnA>
        <columnB>2</columnB>
        <columnC>true</columnC>
    </row>
</data>
```

I can read in the XML file just fine using:
```
import pandas_read_xml as pdx
df = pdx.read_xml("test.xml", root_key_list=["data"])
```

However, if I try to export the resulting DataFrame to CSV...
```
df.to_csv("output.csv", index=False, encoding='cp1252')
```
it produces the following CSV output:
```
row
OrderedDict([('columnA', 'value'), ('columnB', '2'), ('columnC', 'true')])
OrderedDict([('columnA', 'value'), ('columnB', '2'), ('columnC', 'true')])
OrderedDict([('columnA', 'value'), ('columnB', '2'), ('columnC', 'true')])

```

My guess is, that this IS a CSV file, although with a single column (row) and the OrderedDict being the str representation of the dictionary instead of the actual values.

Running on Python 3.8, pandas 1.1.3 and pandas-read-xml 0.0.7.

**Comment by minchulkim87** [comment]
Hey there

Could you please try "flattening" the dataframe before writing out to csv?

```python
df = df.pipe(pdx.fully_flatten)
```

will probably do the trick.

**Comment by cozyGalvinism** [comment]
Heya, that worked better, but still not quite right. It messes up the column names:

```
"row|columnA"|"row|columnB"|"row|columnC"
value|2|true
value|2|true
value|2|true

```

EDIT: I should specify, I use | as separator, though I can change that for debugging this.

**Comment by minchulkim87** [comment]
Hey

Glad it works better.

Actually, the column name thing is by design.
Sometimes entire relational databases are transmitted via XMLs, and this means the tags are often not unique column names. Imagine multiple tables existing in the same XML. Two columns in two different tables can share the same name - a flattening process needs to retain this difference. This means the node tags of the tree-like structure need to be retained during flattening. In fact the way that pandas handles this with JSON explode is similar, but the default concatenation uses "." instead of "|". I chose the pipe separator because tags can often contain periods or hyphens.

Happy to elaborate further, but XMLs are so flexible that they aren't used consistently across its many users. Unlike JSON, the way it needs to be handled is necessarily messier, which is why I suspect pandas does not have a read_xml yet.

To make it a little cleaner, either try

```python
df = pdx.read_xml("test.xml", root_key_list=["data", "row"])
```

(not sure if this works)

or clean the column names after the original method with

```python
df.columns = df.columns.str.replace('row|', '')
```

**Comment by cozyGalvinism** [comment]
Okay, yeah. That's understandable.

Adding the "row" key to the root key list works a charm, thank you!
