### ISSUE TITLE
colab: sample data offline

### ISSUE THREAD

**Issue by rjschmitt** [minchulkim87/pandas_read_xml#8]
Hi,

first of all, thank you for this amazing tool. I wanted to try out the [colab example](https://colab.research.google.com/github/minchulkim87/pandas_read_xml/blob/master/pandas_read_xml_example.ipynb). There are some sample data loaded from https://bulkdata.uspto.gov/data/trademark/dailyxml/applications/apc200219.zip.

Apparently, this link is dead. It would be nice to get this data in order to fully grasp the example and understand the library based upon the example.

Kind regards

**Comment by minchulkim87** [comment]
Hi

Thanks for letting me know!
I've replaced the example with a hardcoded snippet of an example nested XML that I found from an educational page (https://www3.ntu.edu.sg/home/ehchua/programming/java/J6d_xml.html).

Hopefully, that works and clarifies what this tool can and cannot do.

Also, please note that while I created this tool because pandas did not have a .read_xml() method at the time, it looks like we are going to see one soon! Perhaps that means my temporary solution can retire.

Regards
